workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_WORKSPACE: "ios/PingPay.xcworkspace"
        XCODE_SCHEME: "PingPay"
        BUNDLE_ID: "com.pingpay.app"
      node: 18
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Set iOS build number
        script: |
          cd ios
          agvtool new-version -all $CM_BUILD_NUMBER

      - name: Build IPA
        script: |
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/PingPay.xcarchive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/PingPay.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ipa

    artifacts:
      - build/ipa/*.ipa

    publishing:
      app_store_connect:
        apple_id: rcrtavanam@email.com
        submit_to_testflight: true
