workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      node: 18

    scripts:
      - name: Install JS dependencies
        script: |
          npm install

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Create exportOptions.plist
        script: |
          cat <<EOF > export_options.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
           "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
            <key>signingStyle</key>
            <string>automatic</string>
          </dict>
          </plist>
          EOF

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/PingPay.xcodeproj" \
            --scheme "PingPay" \
            --export-options-plist export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
